---
label: Product
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: ID
  description: product ID
- name: name
  type: text
  config:
    required: false
  label: name
  description: product name
- name: price
  type: number
  label: price
  description: product price
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: description
  type: text
  config:
    required: false
  label: description
  description: product description
- name: image
  type: file
  config:
    maxSize: 250
  label: image
  description: product image
- name: product_url
  type: text
  config:
    required: false
  label: product_url
  description: product url
